image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - api_staging
  - app_staging
  - api_production

api_staging:
  type: deploy
  stage: api_staging
  image: ruby:latest
  script:
    - cd ./packages/api
    - dpl --provider=heroku --app=digitalnomads-api --api-key=$HEROKU_API_KEY
  only:
    - branches
  when: manual

app_staging:
  type: deploy
  stage: app_staging
  image: ruby:latest
  script:
    - cd ./packages/app
    - dpl --provider=heroku --app=digitalnomads-app --api-key=$HEROKU_API_KEY
  only:
    - branches
  when: manual

api_production:
  type: deploy
  stage: api_production
  image: ruby:latest
  script:
    - cd ./packages/api
    - dpl --provider=heroku --app=digitalnomads-api --api-key=$HEROKU_API_KEY
  only:
    - master
