const express = require('express')
const router = express.Router()
const multer = require('multer')
const authenticate = require('../utils/authenticate')
const upload = multer()

const signIn = require('../controller/auth/signIn')
const signUp = require('../controller/auth/signUp')
const avatarUpload = require('../controller/auth/avatarUpload')
const avatarDelete = require('../controller/auth/avatarDelete')
const passwordForgot = require('../controller/auth/passwordForgot')
const passwordReset = require('../controller/auth/passwordReset')
const passwordResetValidation = require('../controller/auth/passwordResetValidation')
const passwordChange = require('../controller/auth/passwordChange')
const usernameChange = require('../controller/auth/usernameChange')
const emailChange = require('../controller/auth/emailChange')
const settingsChange = require('../controller/auth/settingsChange')
const sendActivationEmail = require('../controller/auth/sendActivationEmail')
const activateAccount = require('../controller/auth/activateAccount')

router.post('/sign-up', signUp)
router.post('/sign-in', signIn)
router.post('/confirm-email', activateAccount)
router.post('/send-activation-email', sendActivationEmail)
router.post('/avatar-upload', authenticate(), upload.single('avatar'), avatarUpload)
router.post('/avatar-delete', authenticate(), avatarDelete)
router.post('/password-forgot', passwordForgot)
router.post('/password-reset', passwordReset)
router.get('/password-reset-validation/:resetPasswordToken', passwordResetValidation)
router.post('/username-change', authenticate(), usernameChange)
router.post('/password-change', authenticate(), passwordChange)
router.post('/email-change', authenticate(), emailChange)
router.post('/settings-change', authenticate(), settingsChange)

module.exports = router
