const express = require('express')
const router = express.Router()
const multer = require('multer')
const authenticate = require('../utils/authenticate')
const upload = multer()

const login = require('../controller/auth/login')
const register = require('../controller/auth/register')
const avatarUpload = require('../controller/auth/avatarUpload')
const avatarDelete = require('../controller/auth/avatarDelete')
const passwordForgot = require('../controller/auth/passwordForgot')
const passwordReset = require('../controller/auth/passwordReset')
const passwordChange = require('../controller/auth/passwordChange')
const usernameChange = require('../controller/auth/usernameChange')
const emailChange = require('../controller/auth/emailChange')
const settingsChange = require('../controller/auth/settingsChange')

router.post('/register', register)
router.post('/login', login)
router.post('/avatar-upload', authenticate(), upload.single('avatar'), avatarUpload)
router.post('/avatar-delete', authenticate(), avatarDelete)
router.post('/password-forgot', passwordForgot)
router.post('/password-reset', passwordReset)
router.post('/username-change', authenticate(), usernameChange)
router.post('/password-change', authenticate(), passwordChange)
router.post('/email-change', authenticate(), emailChange)
router.post('/settings-change', authenticate(), settingsChange)

module.exports = router
