const express = require('express')
const router = express.Router()
const authenticate = require('../utils/authenticate')

const postCreate = require('../controller/posts/postCreate')
const postUpdate = require('../controller/posts/postUpdate')
const postDelete = require('../controller/posts/postDelete')
const postToggleBookmarks = require('../controller/posts/postToggleBookmarks')
const postToggleLikes = require('../controller/posts/postToggleLikes')
const getAllPosts = require('../controller/posts/getAllPosts')
const getPostsByUserId = require('../controller/posts/getPostsByUserId')
const getPostsByBookmarkedUser = require('../controller/posts/getPostsByBookmarkedUser')
const getPostsByTag = require('../controller/posts/getPostsByTag')
const getPostsByPlaceId = require('../controller/posts/getPostsByPlaceId')
const getAllPostsTags = require('../controller/posts/getAllPostsTags')
const getPostById = require('../controller/posts/getPostById')

router.post('/post-create', authenticate(), postCreate)
router.patch('/post-update', authenticate(), postUpdate)
router.delete('/post-delete', authenticate(), postDelete)
router.post('/post-toggle-likes', authenticate(), postToggleLikes)
router.post('/post-toggle-bookmarks', authenticate(), postToggleBookmarks)
router.get('/get-all-posts', getAllPosts)
router.get('/get-posts-by-user-id/:userId', getPostsByUserId)
router.get('/get-posts-by-place-id/:placeId', getPostsByPlaceId)
router.get('/get-posts-by-bookmarked-user/:userId', getPostsByBookmarkedUser)
router.get('/get-posts-by-tag/:tag', getPostsByTag)
router.get('/get-all-posts-tags', getAllPostsTags)
router.get('/get-post-by-id/:postId', getPostById)

module.exports = router
